// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/6/2025, 2:27:36 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/repos/uj-mvp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/plugins/**/*.{js,ts,mjs}","C:/repos/uj-mvp/frontend/composables/**/*.{js,ts,mjs}","C:/repos/uj-mvp/frontend/utils/**/*.{js,ts,mjs}","C:/repos/uj-mvp/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/repos/uj-mvp/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;